#DROP DATABASE IF EXISTS clientes;

CREATE DATABASE clientes;

USE clientes;

CREATE TABLE cliente (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL
);